### PR TITLE
feat: renamed function name to match name in solution File

### PR DESCRIPTION
**Pull request by Warren-Pitterson**
## Type of changes

- [ x] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

### CODE REVIEW

**Review by will-larkin-nhs — CHANGES_REQUESTED** [review]
need to update compose.yaml

**Review by SamRobinson75684 — DISMISSED** [review]

**Comment by Warren-Pitterson** [comment]
> need to update compose.yaml

RemoveCohortDistributionData is named Correctly in the compose.yaml

**Comment by will-larkin-nhs** [comment]
> > need to update compose.yaml
> 
> RemoveCohortDistributionData is named Correctly in the compose.yaml

Is it not called by other functions? if so, the URL needs renaming in the env variables

**Comment by Warren-Pitterson** [comment]
> > > need to update compose.yaml
> > 
> > 
> > RemoveCohortDistributionData is named Correctly in the compose.yaml
> 
> Is it not called by other functions? if so, the URL needs renaming in the env variables

it's called in the tests and RemoveParticipant.cs, It's named correctly in the dockerfile and i've rename the Environment Variables in both.

image

**Review by will-larkin-nhs — APPROVED** [review]

**Review by andrewmorris43 — APPROVED** [review]
Looks good to me

**Pull request merged**
